# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_delete_member'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='books',
            field=models.ManyToManyField(to='catalogue.Post'),
        ),
    ]
