# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Fine',
            field=models.IntegerField(default=30),
        ),
    ]
