# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20170309_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.Post'),
        ),
    ]
