# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20170310_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hidden_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
