# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallNum', models.CharField(max_length=140)),
                ('Barcode', models.CharField(max_length=140)),
                ('Genre', models.CharField(max_length=140)),
                ('Title', models.CharField(max_length=140)),
                ('Author', models.CharField(max_length=140)),
                ('Status', models.CharField(max_length=140)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
