# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
