# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20170306_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
