# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20170306_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='member_Name',
            field=models.CharField(default=b'Nil', max_length=140, null=True),
        ),
    ]
