# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20170306_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='member_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='Status',
            field=models.CharField(editable=False, max_length=140),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(editable=False),
        ),
    ]
