# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170306_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='member_id',
            new_name='memberid',
        ),
    ]
