# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170306_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='duestatus',
            field=models.IntegerField(choices=[(0, b'OK'), (1, b'DUE')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(editable=False, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
