# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20170308_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Status',
        ),
    ]
