# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_remove_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
