# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
