# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20170314_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
