# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20170314_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
