# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_auto_20170314_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
