# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20170502_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
