# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20170502_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duestatus',
            field=models.IntegerField(choices=[(0, b'OK'), (1, b'DUE')], default=0, editable=False),
        ),
    ]
