# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='id0',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id1',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id10',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id11',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id12',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id13',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id14',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id15',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id16',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id17',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id18',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id19',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id2',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id3',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id4',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id5',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id6',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id7',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id8',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='id9',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
