# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170314_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='book_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
